# Generated by Django 4.2.6 on 2023-11-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.TextField()),
                ('customer_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('shipment_status', models.TextField(default='')),
            ],
        ),
    ]
